const albertaCities = [
  "Airdrie, AB, Canada",
  "Grande Prairie, AB, Canada",
  "Red Deer, AB, Canada",
  "Beaumont, AB, Canada",
  "Hanna, AB, Canada",
  "St. Albert, AB, Canada",
  "Bonnyville, AB, Canada",
  "Hinton, AB, Canada",
  "Spruce Grove, AB, Canada",
  "Brazeau, AB, Canada",
  "Irricana, AB, Canada",
  "Strathcona County, AB, Canada",
  "Breton, AB, Canada",
  "Lacombe, AB, Canada",
  "Strathmore, AB, Canada",
  "Calgary, AB, Canada",
  "Leduc, AB, Canada",
  "Sylvan Lake, AB, Canada",
  "Camrose, AB, Canada",
  "Lethbridge, AB, Canada",
  "Swan Hills, AB, Canada",
  "Canmore, AB, Canada",
  "McLennan, AB, Canada",
  "Taber, AB, Canada",
  "Didzbury, AB, Canada",
  "Medicine Hat, AB, Canada",
  "Turner Valley, AB, Canada",
  "Drayton Valley, AB, Canada",
  "Olds, AB, Canada",
  "Vermillion, AB, Canada",
  "Edmonton, AB, Canada",
  "Onoway, AB, Canada",
  "Wood Buffalo, AB, Canada",
  "Ft. Saskatchewan, AB, Canada",
  "Provost, AB, Canada",
];

const britishColombiaCities = [
  "Burnaby, BC, Canada",
  "Lumby, BC, Canada",
  "City of Port Moody, BC, Canada",
  "Cache Creek, BC, Canada",
  "Maple Ridge, BC, Canada",
  "Prince George, BC, Canada",
  "Castlegar, BC, Canada",
  "Merritt, BC, Canada",
  "Prince Rupert, BC, Canada",
  "Chemainus, BC, Canada",
  "Mission, BC, Canada",
  "Richmond, BC, Canada",
  "Chilliwack, BC, Canada",
  "Nanaimo, BC, Canada",
  "Saanich, BC, Canada",
  "Clearwater, BC, Canada",
  "Nelson, BC, Canada",
  "Sooke, BC, Canada",
  "Colwood, BC, Canada",
  "New Westminster, BC, Canada",
  "Sparwood, BC, Canada",
  "Coquitlam, BC, Canada",
  "North Cowichan, BC, Canada",
  "Surrey, BC, Canada",
  "Cranbrook, BC, Canada",
  "North Vancouver, BC, Canada",
  "Terrace, BC, Canada",
  "Dawson Creek, BC, Canada",
  "Tumbler, BC, Canada",
  "Delta, BC, Canada",
  "Osoyoos, BC, Canada",
  "Vancouver, BC, Canada",
  "Fernie, BC, Canada",
  "Parksville, BC, Canada",
  "Invermere, BC, Canada",
  "Peace River, BC, Canada",
  "Vernon, BC, Canada",
  "Kamloops, BC, Canada",
  "Penticton, BC, Canada",
  "Victoria, BC, Canada",
  "Kaslo, BC, Canada",
  "Port Alberni, BC, Canada",
  "Whistler, BC, Canada",
  "Langley, BC, Canada",
  "Port Hardy, BC, Canada",
];

const manitobaCities = [
  "Birtle, MB, Canada",
  "Flin Flon, MB, Canada",
  "Swan River, MB, Canada",
  "Brandon, MB, Canada",
  "Snow Lake, MB, Canada",
  "The Pas, MB, Canada",
  "Cranberry Portage, MB, Canada",
  "Steinbach, MB, Canada",
  "Thompson, MB, Canada",
  "Dauphin, MB, Canada",
  "Stonewall, MB, Canada",
  "Winnipeg, MB, Canada",
];

const newBrunswickCities = [
  "Cap-Pele, NB, Canada",
  "Miramichi, NB, Canada",
  "Saint John, NB, Canada",
  "Fredericton, NB, Canada",
  "Moncton, NB, Canada",
  "Saint Stephen, NB, Canada",
  "Grand Bay-Westfield, NB, Canada",
  "Oromocto, NB, Canada",
  "Shippagan, NB, Canada",
  "Grand Falls, NB, Canada",
  "Port Elgin, NB, Canada",
  "Sussex, NB, Canada",
  "Memramcook, NB, Canada",
  "Sackville, NB, Canada",
  "Tracadie-Sheila, NB, Canada",
];

const newFoundlandCities = [
  "Argentia, NL, Canada",
  "Corner Brook, NL, Canada",
  "Paradise, NL, Canada",
  "Bishop's Falls, NL, Canada",
  "Labrador City, NL, Canada",
  "Portaux Basques, NL, Canada",
  "Botwood, NL, Canada",
  "Mount Pearl, NL, Canada",
  "St. John's, NL, Canada",
  "Brigus, NL, Canada",
];

const northWestCities = [
  "Town of Hay River, NT, Canada",
  "Town of Inuvik, NW, Canada",
  "Yellowknife, NT, Canada",
];

const novaScotiaCities = [
  "Amherst, NS, Canada",
  "Hants County, NS, Canada",
  "Pictou, NS, Canada",
  "Annapolis, NS, Canada",
  "Inverness County, NS, Canada",
  "Pictou County, NS, Canada",
  "Argyle, NS, Canada",
  "Kentville, NS, Canada",
  "Queens, NS, Canada",
  "Baddeck, NS, Canada",
  "County of Kings, NS, Canada",
  "Richmond, NS, Canada",
  "Bridgewater, NS, Canada",
  "Lunenburg, NS, Canada",
  "Shelburne, NS, Canada",
  "Cape Breton, NS, Canada",
  "Lunenburg County, NS, Canada",
  "Stellarton, NS, Canada",
  "Chester, NS, Canada",
  "Mahone Bay, NS, Canada",
  "Truro, NS, Canada",
  "Cumberland County, NS, Canada",
  "New Glasgow, NS, Canada",
  "Windsor, NS, Canada",
  "East Hants, NS, Canada",
  "New Minas, NS, Canada",
  "Yarmouth, NS, Canada",
  "Halifax, NS, Canada",
  "Parrsboro, NS, Canada",
];

const ontarioCities = [
  "Ajax, ON, Canada",
  "Halton, ON, Canada",
  "Peterborough, ON, Canada",
  "Atikokan, ON, Canada",
  "Halton Hills, ON, Canada",
  "Pickering, ON, Canada",
  "Barrie, ON, Canada",
  "Hamilton, ON, Canada",
  "Port Bruce, ON, Canada",
  "Belleville, ON, Canada",
  "Hamilton-Wentworth, ON, Canada",
  "Port Burwell, ON, Canada",
  "Blandford-Blenheim, ON, Canada",
  "Hearst, ON, Canada",
  "Port Colborne, ON, Canada",
  "Blind River, ON, Canada",
  "Huntsville, ON, Canada",
  "Port Hope, ON, Canada",
  "Brampton, ON, Canada",
  "Ingersoll, ON, Canada",
  "Prince Edward, ON, Canada",
  "Brant, ON, Canada",
  "James, ON, Canada",
  "Quinte West, ON, Canada",
  "Brantford, ON, Canada",
  "Kanata, ON, Canada",
  "Renfrew, ON, Canada",
  "Brock, ON, Canada",
  "Kincardine, ON, Canada",
  "Richmond Hill, ON, Canada",
  "Brockville, ON, Canada",
  "King, ON, Canada",
  "Sarnia, ON, Canada",
  "Burlington, ON, Canada",
  "Kingston, ON, Canada",
  "Sault Ste. Marie, ON, Canada",
  "Caledon, ON, Canada",
  "Kirkland Lake, ON, Canada",
  "Scarborough, ON, Canada",
  "Cambridge, ON, Canada",
  "Kitchener, ON, Canada",
  "Scugog, ON, Canada",
  "Chatham-Kent, ON, Canada",
  "Larder Lake, ON, Canada",
  "Souix Lookout CoC Sioux Lookout, ON, Canada",
  "Chesterville, ON, Canada",
  "Leamington, ON, Canada",
  "Smiths Falls, ON, Canada",
  "Clarington, ON, Canada",
  "Lennox-Addington, ON, Canada",
  "South-West Oxford, ON, Canada",
  "Cobourg, ON, Canada",
  "Lincoln, ON, Canada",
  "St. Catharines, ON, Canada",
  "Cochrane, ON, Canada",
  "Lindsay, ON, Canada",
  "St. Thomas, ON, Canada",
  "Collingwood, ON, Canada",
  "London, ON, Canada",
  "Stoney Creek, ON, Canada",
  "Cornwall, ON, Canada",
  "Loyalist Township, ON, Canada",
  "Stratford, ON, Canada",
  "Cumberland, ON, Canada",
  "Markham, ON, Canada",
  "Sudbury, ON, Canada",
  "Deep River, ON, Canada",
  "Temagami, ON, Canada",
  "Dundas, ON, Canada",
  "Merrickville, ON, Canada",
  "Thorold, ON, Canada",
  "Durham, ON, Canada",
  "Milton, ON, Canada",
  "Thunder Bay, ON, Canada",
  "Dymond, ON, Canada",
  "Nepean, ON, Canada",
  "Tillsonburg, ON, Canada",
  "Ear Falls, ON, Canada",
  "Newmarket, ON, Canada",
  "Timmins, ON, Canada",
  "East Gwillimbury, ON, Canada",
  "Niagara, ON, Canada",
  "Toronto, ON, Canada",
  "East Zorra-Tavistock, ON, Canada",
  "Niagara Falls, ON, Canada",
  "Uxbridge, ON, Canada",
  "Elgin, ON, Canada",
  "Niagara-on-the-Lake, ON, Canada",
  "Vaughan, ON, Canada",
  "Elliot Lake, ON, Canada",
  "North Bay, ON, Canada",
  "Wainfleet, ON, Canada",
  "Flamborough, ON, Canada",
  "North Dorchester, ON, Canada",
  "Wasaga Beach, ON, Canada",
  "Fort Erie, ON, Canada",
  "North Dumfries, ON, Canada",
  "Fort Frances, ON, Canada",
  "North York, ON, Canada",
  "Waterloo, ON, Canada",
  "Gananoque, ON, Canada",
  "Norwich, ON, Canada",
  "Welland, ON, Canada",
  "Georgina, ON, Canada",
  "Oakville, ON, Canada",
  "Wellesley, ON, Canada",
  "Glanbrook, ON, Canada",
  "Orangeville, ON, Canada",
  "West Carleton, ON, Canada",
  "Gloucester, ON, Canada",
  "Orillia, ON, Canada",
  "West Lincoln, ON, Canada",
  "Goulbourn, ON, Canada",
  "Osgoode, ON, Canada",
  "Whitby, ON, Canada",
  "Gravenhurst, ON, Canada",
  "Oshawa, ON, Canada",
  "Wilmot, ON, Canada",
  "Grimsby, ON, Canada",
  "Ottawa, ON, Canada",
  "Windsor, ON, Canada",
  "Guelph, ON, Canada",
  "Ottawa-Carleton, ON, Canada",
  "Woolwich, ON, Canada",
  "Haldimand-Norfork, ON, Canada",
  "Owen Sound, ON, Canada",
  "York, ON, Canada",
];

const peiCities = [
  "Alberton, PE, Canada",
  "Montague, PE, Canada",
  "Stratford, PE, Canada",
  "Charlottetown, PE, Canada",
  "Souris, PE, Canada",
  "Summerside, PE, Canada",
  "Cornwall, PE, Canada",
];

const quebecCities = [
  "Alma, QC, Canada",
  "Fleurimont, QC, Canada",
  "Longueuil, QC, Canada",
  "Amos, QC, Canada",
  "Gaspe, QC, Canada",
  "Marieville, QC, Canada",
  "Anjou, QC, Canada",
  "Gatineau, QC, Canada",
  "Mount Royal, QC, Canada",
  "Aylmer, QC, Canada",
  "Hull, QC, Canada",
  "Montreal, QC, Canada",
  "Beauport, QC, Canada",
  "Joliette, QC, Canada",
  "Montreal Region, QC, Canada",
  "Bromptonville, QC, Canada",
  "Jonquiere, QC, Canada",
  "Montreal-Est, QC, Canada",
  "Brosssard, QC, Canada",
  "Lachine, QC, Canada",
  "Quebec, QC, Canada",
  "Chateauguay, QC, Canada",
  "Lasalle, QC, Canada",
  "Saint-Leonard, QC, Canada",
  "Chicoutimi, QC, Canada",
  "Laurentides, QC, Canada",
  "Sherbrooke, QC, Canada",
  "Coaticook, QC, Canada",
  "LaSalle, QC, Canada",
  "Sorel, QC, Canada",
  "Laval, QC, Canada",
  "Thetford Mines, QC, Canada",
  "Dorval, QC, Canada",
  "Lennoxville, QC, Canada",
  "Victoriaville, QC, Canada",
  "Drummondville, QC, Canada",
  "Levis, QC, Canada",
];

const saskCities = [
  "Avonlea, SK, Canada",
  "Melfort, SK, Canada",
  "Swift Current, SK, Canada",
  "Colonsay, SK, Canada",
  "Nipawin, SK, Canada",
  "Tisdale, SK, Canada",
  "Craik, SK, Canada",
  "Prince Albert, SK, Canada",
  "Unity, SK, Canada",
  "Creighton, SK, Canada",
  "Regina, SK, Canada",
  "Weyburn, SK, Canada",
  "Eastend, SK, Canada",
  "Saskatoon, SK, Canada",
  "Wynyard, SK, Canada",
  "Esterhazy, SK, Canada",
  "Shell Lake, SK, Canada",
  "Yorkton, SK, Canada",
  "Gravelbourg, SK, Canada",
];

const yukonCities = ["Carcross, YK, Canada", "Whitehorse, YK"];

export const canadaCities = [
  ...albertaCities,
  ...britishColombiaCities,
  ...manitobaCities,
  ...newBrunswickCities,
  ...newFoundlandCities,
  ...northWestCities,
  ...novaScotiaCities,
  ...ontarioCities,
  ...peiCities,
  ...quebecCities,
  ...saskCities,
  ...yukonCities,
];
