export const categories = [
  {
    value: "art",
    label: "Art",
    imageSrc: "/illustrations/art.png",
    tags: "drawings, paintings, craft, pencil",
  },
  {
    value: "baking-and-catering",
    label: "Baking / Catering",
    imageSrc: "/illustrations/bake.png",
    tags: "food, cake, dessert, biscuits, loaves, macaroons, sweets, cupcakes, chef, catering, bulk catering, private chef, cuisine",
  },
  {
    value: "coaching-tutoring",
    label: "Coaching / Tutoring",
    imageSrc: "/illustrations/teach.png",
    tags: "tutoring, education, private tutor",
  },
  {
    value: "consultancy",
    label: "Consultancy",
    imageSrc: "/illustrations/consultation.png",
    tags: "legal, financial, taxes, immigration, professional, marketing, career coaching",
  },
  {
    value: "content-creating-and-writing",
    label: "Content Creating / Writing",
    imageSrc: "/illustrations/writing.png",
    tags: "guest blogging, social media",
  },
  {
    value: "entertainment",
    label: "Entertainment",
    imageSrc: "/illustrations/microphone.png",
    tags: "DJ, MC, spoken word, comedy, funny, musician, music band, composer",
  },
  {
    value: "event-planning",
    label: "Event Planning",
    imageSrc: "/illustrations/party-planner.png",
    tags: "weddings, corporate events, virtual events, luxury events, social events",
  },
  {
    value: "fashion",
    imageSrc: "/illustrations/fashion.png",
    label: "Fashion",
    tags: "alterations, bespoke, bridal gowns, tuxedo, prom dresses, fabrics, fashion, stylists, seamstress, tailor",
  },
  {
    value: "fitness",
    label: "Fitness",
    imageSrc: "/illustrations/fitness.png",
    tags: "yoga, work out, coach, gym, instructor, personal trainer",
  },
  {
    value: "graphic-design",
    label: "Graphic Design",
    imageSrc: "/illustrations/computer.png",
    tags: "logo, poster, flyer, banner",
  },
  {
    value: "groceries",
    label: "Groceries",
    imageSrc: "/illustrations/groceries.png",
    tags: "african groceries, grocery delivery, nigerian snacks",
  },
  {
    value: "hair-and-beauty",
    label: "Hair / Beauty",
    imageSrc: "/illustrations/long-wavy-hair-variant.png",
    tags: "wigs, weaves, custom wigs, cornrows, afro, makeup, skincare, eyebrows, eyelashes, hair removal",
  },
  {
    value: "handcraft-gifting",
    label: "Handcraft / Gifting Services",
    imageSrc: "/illustrations/gift-box.png",
    tags: "souvenirs, gift boxes, handmade, customized apparel, favours",
  },
  {
    value: "housekeeping",
    label: "Housekeeping Services",
    imageSrc: "/illustrations/household.png",
    tags: "cleaning, housekeeping, office cleaning, house sitting",
  },
  {
    value: "interior-decor",
    label: "Interior Decor",
    imageSrc: "/illustrations/decor.png",
    tags: "party decor, rennovation, rentals, wedding design, balloons, florals, home decor",
  },
  {
    value: "maintenance-repair",
    label: "Maintenance/Repair Services",
    imageSrc: "/illustrations/tools.png",
    tags: "automotive, plumbing, electrical, carpentry, woodwork, home rennovation, cleaning, furniture assembly, handyman, housekeeping",
  },
  {
    value: "media-services",
    label: "Media services",
    imageSrc: "/illustrations/video-media.png",
    tags: "photographer, potrait, wedding photographer, photoshoot, cinematography, product photography, event media",
  },
  {
    value: "travel-tourism",
    label: "Travel / Tourism Service",
    imageSrc: "/illustrations/around.png",
    tags: "tours, cruise, tourism, explore",
  },
  {
    value: "web-dev-design",
    label: "Web Development / Design",
    imageSrc: "/illustrations/web-programming.png",
    tags: "coding, UI/UX, webapp, website design, webflow, wordpress, shopify, javascript",
  },
  {
    value: "other",
    label: "Other",
    imageSrc: "/illustrations/black-businesses.png",
    tags: "We'll reach out to you to find out more",
  },
];
